#clock
set_property -dict {PACKAGE_PIN AV38 IOSTANDARD LVDS} [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN AU38 IOSTANDARD LVDS} [get_ports sys_clk_p]

#pcie
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pcie_clk_gt]

set_property PACKAGE_PIN AU10 [get_ports pcie_clk_p]
set_property PACKAGE_PIN AU9 [get_ports pcie_clk_n]
set_property -dict {PACKAGE_PIN AU36 IOSTANDARD LVCMOS18} [get_ports pcie_rst_n]


#INPUT

#/******************IIC***************************/
set_property -dict {PACKAGE_PIN AT32 IOSTANDARD LVCMOS18} [get_ports sda_fmc0]
set_property -dict {PACKAGE_PIN AR30 IOSTANDARD LVCMOS18} [get_ports scl_fmc0]
set_property -dict {PACKAGE_PIN U28 IOSTANDARD LVCMOS18} [get_ports sda_fmc1]
set_property -dict {PACKAGE_PIN R29 IOSTANDARD LVCMOS18} [get_ports scl_fmc1]
#EEPROM
set_property -dict {PACKAGE_PIN AN30 IOSTANDARD LVCMOS18} [get_ports sda_master]
set_property -dict {PACKAGE_PIN AP30 IOSTANDARD LVCMOS18} [get_ports scl_master]

#/******************FLASH*************************/
#ctr
set_property -dict {PACKAGE_PIN AL36 IOSTANDARD LVCMOS18} [get_ports flash_ce]
set_property -dict {PACKAGE_PIN BA41 IOSTANDARD LVCMOS18} [get_ports flash_oe]
set_property -dict {PACKAGE_PIN BB41 IOSTANDARD LVCMOS18} [get_ports flash_we]
set_property -dict {PACKAGE_PIN AL32 IOSTANDARD LVCMOS18} [get_ports flash_ry_byn]
#addr
set_property -dict {PACKAGE_PIN AJ28 IOSTANDARD LVCMOS18} [get_ports {flash_addr[0]}]
set_property -dict {PACKAGE_PIN AH28 IOSTANDARD LVCMOS18} [get_ports {flash_addr[1]}]
set_property -dict {PACKAGE_PIN AG31 IOSTANDARD LVCMOS18} [get_ports {flash_addr[2]}]
set_property -dict {PACKAGE_PIN AF30 IOSTANDARD LVCMOS18} [get_ports {flash_addr[3]}]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS18} [get_ports {flash_addr[4]}]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD LVCMOS18} [get_ports {flash_addr[5]}]
set_property -dict {PACKAGE_PIN AG29 IOSTANDARD LVCMOS18} [get_ports {flash_addr[6]}]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS18} [get_ports {flash_addr[7]}]
set_property -dict {PACKAGE_PIN AJ30 IOSTANDARD LVCMOS18} [get_ports {flash_addr[8]}]
set_property -dict {PACKAGE_PIN AH30 IOSTANDARD LVCMOS18} [get_ports {flash_addr[9]}]
set_property -dict {PACKAGE_PIN AH29 IOSTANDARD LVCMOS18} [get_ports {flash_addr[10]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD LVCMOS18} [get_ports {flash_addr[11]}]
set_property -dict {PACKAGE_PIN AL29 IOSTANDARD LVCMOS18} [get_ports {flash_addr[12]}]
set_property -dict {PACKAGE_PIN AN33 IOSTANDARD LVCMOS18} [get_ports {flash_addr[13]}]
set_property -dict {PACKAGE_PIN AM33 IOSTANDARD LVCMOS18} [get_ports {flash_addr[14]}]
set_property -dict {PACKAGE_PIN AM32 IOSTANDARD LVCMOS18} [get_ports {flash_addr[15]}]
set_property -dict {PACKAGE_PIN AV41 IOSTANDARD LVCMOS18} [get_ports {flash_addr[16]}]
set_property -dict {PACKAGE_PIN AU41 IOSTANDARD LVCMOS18} [get_ports {flash_addr[17]}]
set_property -dict {PACKAGE_PIN BA42 IOSTANDARD LVCMOS18} [get_ports {flash_addr[18]}]
set_property -dict {PACKAGE_PIN AU42 IOSTANDARD LVCMOS18} [get_ports {flash_addr[19]}]
set_property -dict {PACKAGE_PIN AT41 IOSTANDARD LVCMOS18} [get_ports {flash_addr[20]}]
set_property -dict {PACKAGE_PIN BA40 IOSTANDARD LVCMOS18} [get_ports {flash_addr[21]}]
set_property -dict {PACKAGE_PIN BA39 IOSTANDARD LVCMOS18} [get_ports {flash_addr[22]}]
set_property -dict {PACKAGE_PIN BB39 IOSTANDARD LVCMOS18} [get_ports {flash_addr[23]}]
set_property -dict {PACKAGE_PIN BB38 IOSTANDARD LVCMOS18} [get_ports {flash_addr[24]}]
set_property -dict {PACKAGE_PIN AY38 IOSTANDARD LVCMOS18} [get_ports {flash_addr[25]}]
#data
set_property -dict {PACKAGE_PIN AM36 IOSTANDARD LVCMOS18} [get_ports {flash_dq[0]}]
set_property -dict {PACKAGE_PIN AN36 IOSTANDARD LVCMOS18} [get_ports {flash_dq[1]}]
set_property -dict {PACKAGE_PIN AJ36 IOSTANDARD LVCMOS18} [get_ports {flash_dq[2]}]
set_property -dict {PACKAGE_PIN AJ37 IOSTANDARD LVCMOS18} [get_ports {flash_dq[3]}]
set_property -dict {PACKAGE_PIN AK37 IOSTANDARD LVCMOS18} [get_ports {flash_dq[4]}]
set_property -dict {PACKAGE_PIN AL37 IOSTANDARD LVCMOS18} [get_ports {flash_dq[5]}]
set_property -dict {PACKAGE_PIN AN35 IOSTANDARD LVCMOS18} [get_ports {flash_dq[6]}]
set_property -dict {PACKAGE_PIN AP35 IOSTANDARD LVCMOS18} [get_ports {flash_dq[7]}]
set_property -dict {PACKAGE_PIN AM37 IOSTANDARD LVCMOS18} [get_ports {flash_dq[8]}]
set_property -dict {PACKAGE_PIN AG33 IOSTANDARD LVCMOS18} [get_ports {flash_dq[9]}]
set_property -dict {PACKAGE_PIN AH33 IOSTANDARD LVCMOS18} [get_ports {flash_dq[10]}]
set_property -dict {PACKAGE_PIN AK35 IOSTANDARD LVCMOS18} [get_ports {flash_dq[11]}]
set_property -dict {PACKAGE_PIN AL35 IOSTANDARD LVCMOS18} [get_ports {flash_dq[12]}]
set_property -dict {PACKAGE_PIN AJ31 IOSTANDARD LVCMOS18} [get_ports {flash_dq[13]}]
set_property -dict {PACKAGE_PIN AH34 IOSTANDARD LVCMOS18} [get_ports {flash_dq[14]}]
set_property -dict {PACKAGE_PIN AJ35 IOSTANDARD LVCMOS18} [get_ports {flash_dq[15]}]

#/*******************UART**********************/#
#set_property -dict {PACKAGE_PIN AP40 IOSTANDARD LVCMOS18} [get_ports {uart_rx[0]}]
#set_property -dict {PACKAGE_PIN AN40 IOSTANDARD LVCMOS18} [get_ports {uart_rx[1]}]
#set_property -dict {PACKAGE_PIN AT37 IOSTANDARD LVCMOS18} [get_ports {uart_rx[2]}]
#set_property -dict {PACKAGE_PIN AN41 IOSTANDARD LVCMOS18} [get_ports {uart_rx[3]}]
#set_property -dict {PACKAGE_PIN AR39 IOSTANDARD LVCMOS18} [get_ports {uart_rx[4]}]
#set_property -dict {PACKAGE_PIN AT36 IOSTANDARD LVCMOS18} [get_ports {uart_rx[5]}]
#set_property -dict {PACKAGE_PIN AU37 IOSTANDARD LVCMOS18} [get_ports {uart_rx[6]}]
#set_property -dict {PACKAGE_PIN AP38 IOSTANDARD LVCMOS18} [get_ports {uart_rx[7]}]

#set_property -dict {PACKAGE_PIN AU33 IOSTANDARD LVCMOS18} [get_ports {uart_tx[0]}]
#set_property -dict {PACKAGE_PIN AM41 IOSTANDARD LVCMOS18} [get_ports {uart_tx[1]}]
#set_property -dict {PACKAGE_PIN AU36 IOSTANDARD LVCMOS18} [get_ports {uart_tx[2]}]
#set_property -dict {PACKAGE_PIN AN39 IOSTANDARD LVCMOS18} [get_ports {uart_tx[3]}]
#set_property -dict {PACKAGE_PIN AU31 IOSTANDARD LVCMOS18} [get_ports {uart_tx[4]}]
#set_property -dict {PACKAGE_PIN AM39 IOSTANDARD LVCMOS18} [get_ports {uart_tx[5]}]
#set_property -dict {PACKAGE_PIN AL31 IOSTANDARD LVCMOS18} [get_ports {uart_tx[6]}]
#set_property -dict {PACKAGE_PIN AN34 IOSTANDARD LVCMOS18} [get_ports {uart_tx[7]}]
#/*******************btc *********************/
set_property -dict {PACKAGE_PIN AM28 IOSTANDARD LVCMOS18} [get_ports btc_tx]
set_property -dict {PACKAGE_PIN AT25 IOSTANDARD LVCMOS18} [get_ports btc_rx]
set_property -dict {PACKAGE_PIN AN25 IOSTANDARD LVCMOS18} [get_ports btc_1pps]
set_property -dict {PACKAGE_PIN AL25 IOSTANDARD LVCMOS18} [get_ports btc_rx_en]
set_property -dict {PACKAGE_PIN AM29 IOSTANDARD LVCMOS18} [get_ports btc_1pps_en]
#/*******************trig *********************/
#set_property -dict {PACKAGE_PIN BB31 IOSTANDARD LVCMOS18} [get_ports ext_trig]
#/*******************jesd_tx *********************/
# set_property -dict {PACKAGE_PIN J1} [get_ports {jesd_txn[0]}]
# set_property -dict {PACKAGE_PIN J2} [get_ports {jesd_txp[0]}]
# set_property -dict {PACKAGE_PIN H3} [get_ports {jesd_txn[1]}]
# set_property -dict {PACKAGE_PIN H4} [get_ports {jesd_txp[1]}]
# set_property -dict {PACKAGE_PIN G1} [get_ports {jesd_txn[2]}]
# set_property -dict {PACKAGE_PIN G2} [get_ports {jesd_txp[2]}]
# set_property -dict {PACKAGE_PIN F3} [get_ports {jesd_txn[3]}]
# set_property -dict {PACKAGE_PIN F4} [get_ports {jesd_txp[3]}]
set_property -dict {PACKAGE_PIN E1} [get_ports {jesd_txn[0]}]
set_property -dict {PACKAGE_PIN E2} [get_ports {jesd_txp[0]}]
set_property -dict {PACKAGE_PIN D3} [get_ports {jesd_txn[1]}]
set_property -dict {PACKAGE_PIN D4} [get_ports {jesd_txp[1]}]
set_property -dict {PACKAGE_PIN C1} [get_ports {jesd_txn[2]}]
set_property -dict {PACKAGE_PIN C2} [get_ports {jesd_txp[2]}]
set_property -dict {PACKAGE_PIN B3} [get_ports {jesd_txn[3]}]
set_property -dict {PACKAGE_PIN B4} [get_ports {jesd_txp[3]}]
set_property -dict {PACKAGE_PIN E9} [get_ports jesd_refclk_n]
set_property -dict {PACKAGE_PIN E10} [get_ports jesd_refclk_p]
set_property -dict {PACKAGE_PIN AD33 IOSTANDARD LVDS} [get_ports jesd_sync0_n]
set_property -dict {PACKAGE_PIN AD32 IOSTANDARD LVDS} [get_ports jesd_sync0_p]
set_property -dict {PACKAGE_PIN K32 IOSTANDARD LVDS} [get_ports jesd_sync1_n]
set_property -dict {PACKAGE_PIN L31 IOSTANDARD LVDS} [get_ports jesd_sync1_p]
set_property -dict {PACKAGE_PIN N31 IOSTANDARD LVDS DIFF_TERM 1} [get_ports jesd_sys_ref_n]
set_property -dict {PACKAGE_PIN P30 IOSTANDARD LVDS DIFF_TERM 1} [get_ports jesd_sys_ref_p]
set_property -dict {PACKAGE_PIN AD35 IOSTANDARD LVDS DIFF_TERM 1} [get_ports jesd_glblclkn]
set_property -dict {PACKAGE_PIN AC34 IOSTANDARD LVDS DIFF_TERM 1} [get_ports jesd_glblclkp]
#/**************************lvds ch0*************************/#
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVDS} [get_ports {lvds_clk_n[0]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVDS} [get_ports {lvds_clk_p[0]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVDS} [get_ports {lvds_data_n[0]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVDS} [get_ports {lvds_data_p[0]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVDS} [get_ports {lvds_data_n[1]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVDS} [get_ports {lvds_data_p[1]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVDS} [get_ports {lvds_data_n[2]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVDS} [get_ports {lvds_data_p[2]}]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVDS} [get_ports {lvds_data_n[3]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVDS} [get_ports {lvds_data_p[3]}]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVDS} [get_ports {lvds_data_n[4]}]
set_property -dict {PACKAGE_PIN N25 IOSTANDARD LVDS} [get_ports {lvds_data_p[4]}]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVDS} [get_ports {lvds_data_n[5]}]
set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVDS} [get_ports {lvds_data_p[5]}]
set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVDS} [get_ports {lvds_data_n[6]}]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVDS} [get_ports {lvds_data_p[6]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVDS} [get_ports {lvds_data_n[7]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVDS} [get_ports {lvds_data_p[7]}]
###/**************************lvds ch1*************************/#
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVDS} [get_ports {lvds_clk_n[1]}]
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVDS} [get_ports {lvds_clk_p[1]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVDS} [get_ports {lvds_data_n[8]}]
set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVDS} [get_ports {lvds_data_p[8]}]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD LVDS} [get_ports {lvds_data_n[9]}]
set_property -dict {PACKAGE_PIN E27 IOSTANDARD LVDS} [get_ports {lvds_data_p[9]}]
set_property -dict {PACKAGE_PIN F31 IOSTANDARD LVDS} [get_ports {lvds_data_n[10]}]
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVDS} [get_ports {lvds_data_p[10]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVDS} [get_ports {lvds_data_n[11]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVDS} [get_ports {lvds_data_p[11]}]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVDS} [get_ports {lvds_data_n[12]}]
set_property -dict {PACKAGE_PIN D30 IOSTANDARD LVDS} [get_ports {lvds_data_p[12]}]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVDS} [get_ports {lvds_data_n[13]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVDS} [get_ports {lvds_data_p[13]}]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVDS} [get_ports {lvds_data_n[14]}]
set_property -dict {PACKAGE_PIN F29 IOSTANDARD LVDS} [get_ports {lvds_data_p[14]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVDS} [get_ports {lvds_data_n[15]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVDS} [get_ports {lvds_data_p[15]}]

set_property DIFF_TERM true [get_ports lvds_*]
#/**************************lvds ch2*************************/#
#set_property PACKAGE_PIN D21 [get_ports {lvds_clk_n[2]}]
#set_property PACKAGE_PIN D20 [get_ports {lvds_clk_p[2]}]
#set_property PACKAGE_PIN C23 [get_ports {lvds_data_n[16]}]
#set_property PACKAGE_PIN C22 [get_ports {lvds_data_p[16]}]
#set_property PACKAGE_PIN H23 [get_ports {lvds_data_n[17]}]
#set_property PACKAGE_PIN H22 [get_ports {lvds_data_p[17]}]
#set_property PACKAGE_PIN G22 [get_ports {lvds_data_n[18]}]
#set_property PACKAGE_PIN G21 [get_ports {lvds_data_p[18]}]
#set_property PACKAGE_PIN H26 [get_ports {lvds_data_n[19]}]
#set_property PACKAGE_PIN H25 [get_ports {lvds_data_p[19]}]
#set_property PACKAGE_PIN G25 [get_ports {lvds_data_n[20]}]
#set_property PACKAGE_PIN G24 [get_ports {lvds_data_p[20]}]
#set_property PACKAGE_PIN D24 [get_ports {lvds_data_n[21]}]
#set_property PACKAGE_PIN D23 [get_ports {lvds_data_p[21]}]
#set_property PACKAGE_PIN H29 [get_ports {lvds_data_n[22]}]
#set_property PACKAGE_PIN H28 [get_ports {lvds_data_p[22]}]
#set_property PACKAGE_PIN G28 [get_ports {lvds_data_n[23]}]
#set_property PACKAGE_PIN G27 [get_ports {lvds_data_p[23]}]
#s/**************************lvds ch3*************************/#
#set_property PACKAGE_PIN K26 [get_ports {lvds_clk_n[3]}]
#set_property PACKAGE_PIN K25 [get_ports {lvds_clk_p[3]}]
#set_property PACKAGE_PIN J25 [get_ports {lvds_data_n[24]}]
#set_property PACKAGE_PIN J24 [get_ports {lvds_data_p[24]}]
#set_property PACKAGE_PIN F23 [get_ports {lvds_data_n[25]}]
#set_property PACKAGE_PIN F22 [get_ports {lvds_data_p[25]}]
#set_property PACKAGE_PIN E22 [get_ports {lvds_data_n[26]}]
#set_property PACKAGE_PIN E21 [get_ports {lvds_data_p[26]}]
#set_property PACKAGE_PIN F26 [get_ports {lvds_data_n[27]}]
#set_property PACKAGE_PIN F25 [get_ports {lvds_data_p[27]}]
#set_property PACKAGE_PIN E25 [get_ports {lvds_data_n[28]}]
#set_property PACKAGE_PIN E24 [get_ports {lvds_data_p[28]}]
#set_property PACKAGE_PIN K29 [get_ports {lvds_data_n[29]}]
#set_property PACKAGE_PIN K28 [get_ports {lvds_data_p[29]}]
#set_property PACKAGE_PIN J28 [get_ports {lvds_data_n[30]}]
#set_property PACKAGE_PIN J27 [get_ports {lvds_data_p[30]}]
#set_property PACKAGE_PIN F29 [get_ports {lvds_data_n[31]}]
#set_property PACKAGE_PIN F28 [get_ports {lvds_data_p[31]}]
#/**************************ad 9467*************************/#
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS18} [get_ports adc_a9467_1_cs]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS18} [get_ports adc_a9467_1_sck]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS18} [get_ports adc_a9467_1_miso]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS18} [get_ports adc_a9467_1_mosi]

set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS18} [get_ports adc_a9467_2_cs]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS18} [get_ports adc_a9467_2_sck]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS18} [get_ports adc_a9467_2_miso]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS18} [get_ports adc_a9467_2_mosi]
#/**************************ad9516 pll*************************/#
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS18} [get_ports pll_ad9516_cs]
set_property -dict {PACKAGE_PIN C28 IOSTANDARD LVCMOS18} [get_ports pll_ad9516_sck]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS18} [get_ports pll_ad9516_miso]
set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS18} [get_ports pll_ad9516_mosi]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS18} [get_ports pll_ad9516_reset_pin]
#set_property -dict {PACKAGE_PIN C23 IOSTANDARD LVCMOS18} [get_ports gm4526_select]
#/**************************spi 9172*************************/#
set_property -dict {PACKAGE_PIN B38 IOSTANDARD LVCMOS18} [get_ports dac_ad9172_sck]
set_property -dict {PACKAGE_PIN C38 IOSTANDARD LVCMOS18} [get_ports dac_ad9172_cs]
set_property -dict {PACKAGE_PIN A39 IOSTANDARD LVCMOS18} [get_ports dac_ad9172_miso]
set_property -dict {PACKAGE_PIN B39 IOSTANDARD LVCMOS18} [get_ports dac_ad9172_mosi]
set_property -dict {PACKAGE_PIN C39 IOSTANDARD LVCMOS18} [get_ports dac_ad9172_reset_pin]
#/*******************hmc_7044 *********************/
set_property -dict {PACKAGE_PIN G36 IOSTANDARD LVCMOS18} [get_ports pll_hmc7044_sck]
set_property -dict {PACKAGE_PIN F37 IOSTANDARD LVCMOS18} [get_ports pll_hmc7044_reset_pin]
set_property -dict {PACKAGE_PIN F36 IOSTANDARD LVCMOS18} [get_ports pll_hmc7044_cs]
set_property -dict {PACKAGE_PIN J37 IOSTANDARD LVCMOS18} [get_ports pll_hmc7044_mosi]
set_property -dict {PACKAGE_PIN J38 IOSTANDARD LVCMOS18} [get_ports pll_hmc7044_miso]
#fre
set_property -dict {PACKAGE_PIN AT27 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_cs]
set_property -dict {PACKAGE_PIN AU29 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_sck]
set_property -dict {PACKAGE_PIN AV28 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_mosi]
set_property -dict {PACKAGE_PIN AY30 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_miso]
set_property -dict {PACKAGE_PIN AV30 IOSTANDARD LVCMOS18} [get_ports rf_power_en]
set_property -dict {PACKAGE_PIN BB31 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_full_warm0]
set_property -dict {PACKAGE_PIN AW31 IOSTANDARD LVCMOS18} [get_ports rx_zd20e_full_warm1]

set_property -dict {PACKAGE_PIN AJ26 IOSTANDARD LVCMOS18} [get_ports tx_zc18_cs]
set_property -dict {PACKAGE_PIN AL27 IOSTANDARD LVCMOS18} [get_ports tx_zc18_sck]
set_property -dict {PACKAGE_PIN AK24 IOSTANDARD LVCMOS18} [get_ports tx_zc18_mosi]
set_property -dict {PACKAGE_PIN AK27 IOSTANDARD LVCMOS18} [get_ports tx_zc18_miso]
#**********************************other**********************#

set_property -dict {PACKAGE_PIN J36 IOSTANDARD LVCMOS18} [get_ports da_chn0_en]
set_property -dict {PACKAGE_PIN H36 IOSTANDARD LVCMOS18} [get_ports da_chn1_en]

set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS18} [get_ports fmc_ad_pll_pwr_ctrl]
set_property -dict {PACKAGE_PIN C23 IOSTANDARD LVCMOS18} [get_ports fmc_ad_pll_sel]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports fmc_ad_ext_trig]

set_property -dict {PACKAGE_PIN AU33 IOSTANDARD LVCMOS18} [get_ports bd_rstn]
set_property -dict {PACKAGE_PIN AT34 IOSTANDARD LVCMOS18} [get_ports bd_pps]
set_property -dict {PACKAGE_PIN AR34 IOSTANDARD LVCMOS18} [get_ports bd_rx]
set_property -dict {PACKAGE_PIN AR33 IOSTANDARD LVCMOS18} [get_ports bd_tx]

#set_property -dict {PACKAGE_PIN AV30 IOSTANDARD LVCMOS18} [get_ports v7_12v_en]

