create_clock -period 10.000 -name sys_clk_p [get_ports sys_clk_p]
create_clock -period 10.000 -name pcie_clk_p [get_ports pcie_clk_p]
create_clock -period 5.357 -name lvds_clk0 [get_ports {lvds_clk_p[0]}]
create_clock -period 5.357 -name lvds_clk1 [get_ports {lvds_clk_p[1]}]
create_clock -period 10.714 -name refclk [get_ports jesd_refclk_p]
create_clock -period 10.714 -name glblclk [get_ports jesd_glblclkp]

set_clock_groups -asynchronous -group [get_clocks lvds_clk1] -group [get_clocks lvds_clk0]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks clk_200m_sys_clk_wiz]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks clk_pll_i]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks glblclk]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks lvds_clk0]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks lvds_clk1]
set_clock_groups -asynchronous -group [get_clocks clk_200m_sys_clk_wiz] -group [get_clocks lvds_clk0]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks userclk2]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks clk_125mhz_mux_x0y1]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks clk_250mhz_mux_x0y1]
set_clock_groups -asynchronous -group [get_clocks userclk2] -group [get_clocks clk_125mhz_mux_x0y1]
set_clock_groups -asynchronous -group [get_clocks userclk2] -group [get_clocks clk_250mhz_mux_x0y1]
set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks clk_out1_DAC_division]
set_clock_groups -asynchronous -group [get_clocks clk_out1_DAC_division] -group [get_clocks glblclk]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_mux_x0y0] -group [get_clocks clk_125mhz_x0y0]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_x0y0] -group [get_clocks clk_125mhz_mux_x0y0]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz_x0y0] -group [get_clocks clk_250mhz_mux_x0y0]
set_clock_groups -asynchronous -group [get_clocks userclk2] -group [get_clocks clk_125mhz_mux_x0y0]
set_clock_groups -asynchronous -group [get_clocks userclk2] -group [get_clocks clk_250mhz_mux_x0y0]
set_clock_groups -asynchronous -group [get_clocks clk_out1_DAC_division] -group [get_clocks refclk]
set_clock_groups -asynchronous -group [get_clocks clk_50m_sys_clk_wiz] -group [get_clocks clk_100m_sys_clk_wiz]
set_clock_groups -asynchronous -group [get_clocks clk_50m_sys_clk_wiz] -group [get_clocks clk_out1_DAC_division]
set_clock_groups -asynchronous -group [get_clocks clk_50m_sys_clk_wiz] -group [get_clocks lvds_clk0]
set_clock_groups -asynchronous -group [get_clocks clk_50m_sys_clk_wiz] -group [get_clocks clk_pll_i]
set_clock_groups -asynchronous -group [get_clocks clk_50m_sys_clk_wiz] -group [get_clocks userclk2]

set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks clk_out1_AD_division]
set_clock_groups -asynchronous -group [get_clocks clk_out1_AD_division] -group [get_clocks lvds_clk0]
set_clock_groups -asynchronous -group [get_clocks clk_pll_i] -group [get_clocks mmcm_ps_clk_bufg_in]

set_clock_groups -asynchronous -group [get_clocks clk_100m_sys_clk_wiz] -group [get_clocks clk_out1_DAC_division]
set_clock_groups -asynchronous -group [get_clocks clk_out1_DAC_division] -group [get_clocks glblclk]
set_clock_groups -asynchronous -group [get_clocks refclk] -group [get_clocks -of_objects [get_pins u_sys_clk_wiz_inst/inst/mmcm_adv_inst/CLKOUT1]]

